### ISSUE TITLE
Download link doesnt work

### ISSUE THREAD

**Issue by ploca14** [uxsoft/AppleWirelessKeyboard#12]
Download link is broken

**Comment by uxsoft** [comment]
Try now :-)

**Comment by ploca14** [comment]
Thank you :)

**Comment by tholu** [comment]
Close this issue? :-) Is the project actively maintained?

**Comment by FelixAkk** [comment]
@uxsoft could you have a look at the download link? 🙏  :) 

Perhaps worth using GitHub to host the executable like this fork does? (https://github.com/gered/AppleWirelessKeyboard)

**Comment by uxsoft** [comment]
I put some CI/CD on to make it build automatically and put it into the GitHub releases. I'll update the link in the website.

Thanks for sharing the fork I guess I should also investigate what changes have been made and maybe incorporate them in this project.

**Comment by FelixAkk** [comment]
Awesome! Would be great if you can pick the gems from that fork and incorporate them :) love that attitude of convergence.

Btw, I'm currently running the beforementioned fork, and it works wonderful with my model A1243 keyboard! (which even Magic Utilities doesn't support) I haven't checked out the differences yet, but I suppose most credits actually go to you, so I'll probably send you a donation for open sourcing your work ;)
