### ISSUE TITLE
Settings not saving properly 

### ISSUE THREAD

**Issue by brianx87** [uxsoft/AppleWirelessKeyboard#15]
Every time the software loads it's using a different set of savings from a previous install and now changing settings doesn't work. I have all settings set to work only when function key is pressed but now settings work in both states, settings work when not using Fn key without overlay and with Fn key including overlay. Also brightness setting works in this version where it did not in an older version and this setting I can't seem to change even though I do not require it.

I would prefer all Function keys to act as normal F1-F12 and only use F7-F12 as media and volume control with Fn key pressed. This worked fine on an older version.

**Comment by uxsoft** [comment]
Can you please try if the issue persists in v2.0.15?

https://github.com/uxsoft/AppleWirelessKeyboard/releases/tag/v2.0.15
