### ISSUE TITLE
Crashing as it opens

### ISSUE THREAD

**Issue by Razer0123** [uxsoft/AppleWirelessKeyboard#17]
Tested on latest W10, it opens, but crashes after 5 seconds on the tray

**Comment by reznikartem** [comment]
Same problem. I'm try to compile from sources, exception throws in file 

AppleWirelessKeyboard/AppleWirelessKeyboard/Keyboard/Apple/AppleKeyboardHID2.cs at line 153

"The supplied user buffer is not valid for the requested operation"

I'm very bad in c# :(
How can i help you with fix? Thank you!

**Comment by moxx** [comment]
same issue here on Windows 10 Version 1909

**Comment by uxsoft** [comment]
Can you please try v2.0.15?

https://github.com/uxsoft/AppleWirelessKeyboard/releases/tag/v2.0.15
