### ISSUE TITLE
Set FMode as default when starting

### ISSUE THREAD

**Issue by eXaminator** [uxsoft/AppleWirelessKeyboard#24]
Hi, thanks a lot for this great tool!

I'm using an older (wired) keyboard where fn doesn't work, so I'm using the FMode for that. It would be great if the tool hat a setting to allow it so enable fn mode by default when starting it up, instead to have to toggle it on first!

**Comment by uxsoft** [comment]
Hi,

I added a feature to do this in the configuration in v2.0.16.

https://github.com/uxsoft/AppleWirelessKeyboard/releases/tag/v2.0.16
