### ISSUE TITLE
How to compile this project?

### ISSUE THREAD

**Issue by roelvan** [uxsoft/AppleWirelessKeyboard#4]
Instructions on how to compile the code would be useful as the download link is broken on the project's website. Thanks a lot for this open source project!

**Comment by roelvan** [comment]
Or maybe you could add the .exe to the releases in Github?

**Comment by uxsoft** [comment]
Hi, I fixed the download link. My bad.

As for building the source you can use Visual Studio, or the .NET SDK command line tools. 

msbuild /p:Configuration=Release AppleWirelessKeyboard.sln

**Comment by roelvan** [comment]
Thanks for updating that link! The software doesn't work with my Magic Keyboard though. I tried rebooting and playing with the configuration. It randomly shuts down too. I am using Windows 10.

**Comment by globalviking** [comment]
Thanks for this software. Build, dependency and install instructions should be in README.md.
I'm installing Visual Studio now. In the installed I have many options. Do I need "Universal Windows Platform Development", ".NET Desktop Development" or "Desktop Development with C++"?

**Comment by uxsoft** [comment]
Only the .NET option

**Comment by globalviking** [comment]
Thanks! 😃
