### ISSUE TITLE
Make link from http://applewirelesskbrd.codeplex.com work

### ISSUE THREAD

**Issue by masters3d** [uxsoft/AppleWirelessKeyboard#9]
The link on codeplex is dead http://uxsoft.cz/projects/apple-wireless-keyboard/

Can you please make that link go to your current link? 

It was hard finding this github repo because the link was dead.

**Comment by masters3d** [comment]
the current link is: http://uxsoft.cz/Projects/AppleWirelessKeyboard

**Comment by uxsoft** [comment]
codeplex has been retired ill put the correct link here on github, thanks!
